去除可能存在的系统栏遮罩、去除点击猜版Spinner就隐藏软键盘的逻辑、关于页作者添加“其他贡献者”
klxiaoniu/QQVersionList pull request #29
Opened 2024-04-02 02:26 UTC by ArcticFoxPro

- 去除可能存在的系统栏遮罩
- 去除点击猜版 Spinner 就隐藏软键盘的逻辑
- 关于页作者添加“其他贡献者”

2024-04-02 02:30 UTC, klxiaoniu requested changes

2024-04-02 02:30 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
> +                            it.versionName + "(" + (if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) it.longVersionCode else it.versionCode) + ")"
不要随便删换行，这里的suppress会失效，调一下你的IDE设置

2024-04-02 02:30 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
> +                    val dialogSetting = MaterialAlertDialogBuilder(this).setTitle("设置")
链式调用的换行不要去掉，太丑了

2024-04-02 02:35 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
> +                    val dialogSetting = MaterialAlertDialogBuilder(this).setTitle("设置")
🥺

2024-04-03 10:46 UTC, ArcticFoxPro commented
猜版小版本号 5 的倍数判断存在空对象异常

2024-04-03 12:57 UTC, merged