新增 Shiply 平台更新获取支持（实验性），新增正式版猜版默认添加对“_64_BBPJ”、“_BBPJ_64”后缀的支持，修复不填写主版本号也会尝试拼接字符串并请求服务器的 Bug，修复猜版对话框在小屏幕设备上无法显示完整的 Bug，强制 BottomAppBar 显示完整动作按钮，首页右下角浮动按钮文案由“猜版 Extd.”换回“猜版”
klxiaoniu/QQVersionList pull request #56
Opened 2024-07-14 09:04 UTC by ArcticFoxPro

> [!important]
> ## 前言：请在合并 PR 时避免压缩合并此 PR
>
> 请在合并 PR 时**避免压缩合并此 PR**，这将导致使用内部测试版本用户无法安装新版本。
> 
> 因为压缩合并会降低提交 Git Commit 总数，而 `versionCode` 构建依赖于 Git Commit 总数，导致内部测试版本的 `versionCode` 在一段提交次数内会大于主线版本。

## 这个 PR 解决了什么问题？

> 请补充以下信息

### 需求背景

1. Android QQ 使用 TDS 腾讯端服务（Tencent Device-oriented Service）Shiply 发布平台根据预设的 QQ 号码及配置库分发更新包。此类更新分发包含一种标识为“LiteGray”的小范围灰度更新包，不会包含在 `downv6.qq.com` 下载服务器中。在 1.3.2 版本及以前版本的 QVT 的常规枚举方法无法获取到此类更新。
2. 1.3.2 版本及以前版本的 QVT 存在不填写主版本号也会尝试拼接字符串并请求服务器的 Bug。
3. 1.3.2 版本及以前版本的 QVT 的猜版对话框和设置对话框在小屏幕设备上无法显示完整。
4. 1.3.2 版本及以前版本的 QVT 的 BottomAppBar 在部分机型无法显示完整动作按钮，会溢出成为菜单
5. 1.3.2 版本及以前版本的 QVT 正式版猜版时默认不包含 `_64_BBPJ`、`_BBPJ_64` 后缀。

### 更新日志

#### 修复

- 修复：不填写主版本号也会尝试拼接字符串并请求服务器的 Bug
- 修复：猜版对话框在小屏幕设备上无法显示完整的 Bug，现在可以通过滚动以浏览对话框完整内容

#### 新增

- 新增：实验性支持对 TDS 腾讯端服务（Tencent Device-oriented Service）Shiply 发布平台分发更新安装包直链的获取
    - 支持自动对 Shiply 平台返回内容包含的 Android 应用安装包下载直链进行识别和置顶推荐，点击或长按推荐卡片即可快捷复制。
    - 腾讯 QQ 使用 TDS 腾讯端服务 Shiply 发布平台，根据 QQ 号（uin）及其终端信息分发小范围灰度测试安装包。此功能并非每次请求都能成功获取到更新数据，无法获取更新数据则表示填写的参数不在 Shiply 平台认可与分发范围内。
    - **此功能为 QQ 版本列表实用工具附带的实验性功能，可能存在不可预知的稳定性问题。QQ 版本列表实用工具不对此功能及其任何后果作出任何可靠性保证。请明确并确保自身具备足够的风险识别和承受能力。**
    - 参考自 https://github.com/callng/GQUL ，特别感谢项目作者 @callng 提供的思路。
- 新增：正式版猜版默认添加对 `_64_BBPJ`、`_BBPJ_64` 后缀的支持

#### 优化

- 优化：强制 BottomAppBar 显示完整动作按钮

#### 其它更改

- 为避免遮挡 BottomAppBar 显示动作按钮，首页右下角浮动按钮文案由“猜版 Extd.”换回“猜版”，实际效果不变
- 关于界面新增特别感谢 @callng 

#### 上游更改

- 更新：Gradle 更新至 8.9
- 更新：Android Gradle Plugin 更新至 8.5.1
- 更新：Jetpack Lifecycle KTX（`androidx.lifecycle:lifecycle-runtime-ktx`）更新至 2.8.3
- 新增：OkHttp3 Logging Interceptor（`com.squareup.okhttp3:logging-interceptor`）4.12.0
- 重新添加：Google Gson（`com.google.code.gson:gson`）2.11.0

## 自检清单

> 请检查下列所有选项并打勾

- [x] 此 PR 已实现我的所有预期更改，可以被合并。
- [x] 我确认此 PR 全部代码仅由本人（或联合作者）编写，代码所有权归本人（或联合作者）所有。
- [x] 此 PR 更新日志已提供（或无须提供）。
- [x] Readme 文档无须补充（或已补充）。

2024-07-14 09:43 UTC, klxiaoniu requested changes

2024-07-14 09:43 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/ClipboardUtil.kt
这里直接改成Context.copyText()就可以了

2024-07-14 09:43 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
> +//import android.util.Base64
不需要的导入可以直接Ctrl+Alt+O优化掉，commit设置里也可以优化导入，这里注释看起来不好看

2024-07-14 09:46 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
> +//import android.util.Base64
哦，这里我没看到，当时在试 Ktor，注释掉了这条，没还原

2024-07-15 05:25 UTC, klxiaoniu commented
activity也是一种context，ContextUtil保留一个Context.copy就可

2024-07-17 01:50 UTC, merged