新增 TIM 版本列表，新增“基于 QQNT 技术架构”标识
klxiaoniu/QQVersionList pull request #75
Opened 2024-09-12 03:31 UTC by ArcticFoxPro

## 这个 PR 解决了什么问题？

> 请补充以下信息

### 更新日志

#### 新增

- 新增：TIM 版本列表，进入应用后从右向左滑动版本列表可切换到 TIM 版本列表
- 新增：本机应用版本信息长按查看详情新增对 Target SDK、Min SDK、Compile SDK 的查看
- 新增：QQ 版本列表的“基于 QQNT 技术架构”标识

#### 其它更改

- 本机应用版本信息长按查看详情界面的细微更改
- 由于仅 QQ 版本列表含有额定文件大小信息，对设置文案进行了细微更改以符合实际
- 进行各种小的重构，提高代码质量和可维护性

#### 上游更改

- 新增：Jetpack ViewPager2（`androidx.viewpager2:viewpager2`）1.1.0
- 新增：Jetpack Fragment KTX（`androidx.fragment:fragment-ktx`）1.8.3
- 更新：Gradle 更新至 8.10.1
- 更新：Jetpack Lifecycle Runtime KTX（`androidx.lifecycle:lifecycle-runtime-ktx`）更新至 2.8.5

## 自检清单

> 请确认下列所有选项并打勾

- [x] 此 PR 已实现我的所有预期更改，可以被合并。
- [x] 我确认此 PR 全部代码仅由本人（或联合作者）编写，代码所有权归本人（或联合作者）所有。
- [x] 此 PR 更新日志已提供（或无须提供）。
- [x] Readme 文档无须补充（或已补充）。

> 请确认下列选项并打勾。如不认可选项内容或存在需备注内容，请在选项旁随附补充说明。

- [x] 我认可并确认我贡献的代码将以 [GNU Affero General Public License Version 3](https://github.com/klxiaoniu/QQVersionList/blob/master/LICENSE) 开源许可进行发行。
- （单项选择）若后续项目决定更改开源许可：
  - [ ] 请通知我并等待我的决定
  - [x] 无需通知，我授权项目所有者自行决定我的贡献的开源许可变更。
  - [ ] 其他，请补充说明：_______

2024-09-13 09:19 UTC, klxiaoniu requested changes
粗略地看了一看，代码有点屎山了

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
这个文件太大了，考虑把不同的功能拆到别的类去，eg设置处理逻辑单拉一个类出来

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
大到github默认不渲染这个文件的改变！

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/ShiplyUrlListAdapter.kt
> +        val shiplyUrlText: TextView = itemView.findViewById(R.id.shiply_url_text)
建议用ViewBinding

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/TIMVersionAdapter.kt
> +            0 -> {
魔数，建议定义为常量

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/TIMVersionAdapter.kt
> +                        ).show()
id太长
else块内有多行代码的时候建议用{}包起来

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/TIMVersionAdapter.kt
> +                        ).show()
跟上面一样的代码写了两遍

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/ShiplyAdvancedConfigSheetFragment.kt
> +                    )
一次性put的东西非常多，有没有考虑做一个批量put的方法呢？

2024-09-13 09:19 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/ClipboardUtil.kt
> +     */
意义不明的注释哈，有点太显然了，一眼懂的可以不必写

2024-09-13 09:38 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/TIMVersionAdapter.kt
> +            0 -> {
这个逻辑不是我写的

2024-09-13 09:49 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/ShiplyAdvancedConfigSheetFragment.kt
> +                    )
我在 DataStoreUtil 封装个批量方法吧

2024-09-13 09:54 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/TIMVersionBeanUtil.kt
> +    fun timVersionBeanUtil(thisActivity: MainActivity, responseData: String) {
我知道，你把方法名改改，反映一下具体功能，哪有方法叫xxxUtil的

2024-09-13 09:55 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/TIMVersionAdapter.kt
> +            0 -> {
> 这个逻辑不是我写的

我自己写的我当然认得出来，现在代码量持续增大的情况下有必要写清楚点

2024-09-13 12:11 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/ui/MainActivity.kt
GitHub 默认不渲染长文件的改变很正常吧？如果默认渲染，阅读代码就要滚动一段时间。

整个项目应该已经一万多行代码了（包括媒体资源文件），并且这个项目只有一个 Activity（因为项目太简单也用不到第二个 Activity），感觉一千多行 MainActivity 是可以接受的。并且我已经把不直接处理根组件的代码移出去了，以前有两千多行。

2024-09-13 12:23 UTC, ArcticFoxPro commented
🥺

2024-09-15 11:11 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/VersionBeanUtil.kt
> +    fun qqVersionBeanProcessor(thisActivity: MainActivity, responseData: String) {
一个方法名再怎么样也应该是个动词吧？我前面是不是没表达清楚？

2024-09-15 13:03 UTC, merged