新增从腾讯服务器配置拉取微信最新测试版下载直链的实验性功能，修复无障碍高对比度下的一处界面 Bug，修复特殊桌面图标的单色图标透明度异常，腾讯应用宝更新获取返回内容对话框采用了更简洁可读的界面
klxiaoniu/QQVersionList pull request #89
Opened 2024-11-11 03:24 UTC by ArcticFoxPro

## 这个 PR 解决了什么问题？

> 请补充以下信息

### 需求背景

1. Android 微信测试版相关信息配置在[腾讯服务器配置文件](https://dldir1.qq.com/weixin/android/weixin_android_alpha_config.json)内。
2. 无障碍高对比度下本机 TIM“基于 Android QQ x.x.xx 二次开发”存在界面显示可读性异常。

### 更新日志

#### 修复

- 修复：无障碍高对比度下本机 TIM“基于 Android QQ x.x.xx 二次开发”存在界面显示可读性异常
- 修复：特殊桌面图标的单色图标透明度异常

#### 新增

- 新增：从腾讯服务器配置拉取微信最新测试版下载直链的实验性功能

#### 优化

- 优化：腾讯应用宝更新获取返回内容对话框采用了更简洁可读的界面

#### 上游更改

- 更新：迁移 Coil 2（`io.coil-kt:coil`）2.7.0 至 Coil 3（`io.coil-kt.coil3:coil`）3.0.2
- 新增：Coil 3 Network OkHttp（`io.coil-kt.coil3:coil-network-okhttp`）3.0.2

## 自检清单

> 请确认下列所有选项并打勾

- [x] 此 PR 已实现我的所有预期更改，可以被合并。
- [x] 我确认此 PR 全部代码仅由本人（或联合作者）编写，代码所有权归本人（或联合作者）所有。
- [x] 此 PR 更新日志已提供（或无须提供）。
- [x] Readme 文档无须补充（或已补充）。

> 请确认下列选项并打勾。如不认可选项内容或存在需备注内容，请在选项旁随附补充说明。

- [x] 我认可并确认我贡献的代码将以 [GNU Affero General Public License Version 3](https://github.com/klxiaoniu/QQVersionList/blob/master/LICENSE) 开源许可进行发行。
- （单项选择）若后续项目决定更改开源许可：
  - [ ] 请通知我并等待我的决定
  - [x] 无需通知，我授权项目所有者自行决定我的贡献的开源许可变更。
  - [ ] 其他，请补充说明：_______

2024-11-11 15:14 UTC, klxiaoniu requested changes

2024-11-11 15:14 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +
toast不需要activity就能展示，这边改成直接用全局的ApplicationContext吧，也不需要runOnUiThread了

2024-11-11 15:14 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +        activity?.runOnUiThread {
这里这样改动的目的是什么，为了在fragment里调用的时候少写一句requireActivity()吗？那我也感觉没方便多少，而且没看到有这样用的地方，传过来的都是activity

2024-11-12 14:47 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +        activity?.runOnUiThread {
现在有了，在 `getQua()` 里

2024-11-12 15:56 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +        activity?.runOnUiThread {
> 现在有了，在 `getQua()` 里

这方法唯一一处使用传入的是不是activity?
不能为了改而改

2024-11-12 15:59 UTC, ArcticFoxPro commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +        activity?.runOnUiThread {
> > 现在有了，在 `getQua()` 里
> 
> 这方法唯一一处使用传入的是不是activity?
> 不能为了改而改

😭以后总有在非 Activity 中使用的场景吧，为什么不能 Context 啊

2024-11-12 16:03 UTC, klxiaoniu commented on app/src/main/java/com/xiaoniu/qqversionlist/util/InfoUtil.kt
> +        activity?.runOnUiThread {
> > > 现在有了，在 `getQua()` 里
> > 
> > 
> > 这方法唯一一处使用传入的是不是activity?
> > 不能为了改而改
> 
> 😭以后总有在非 Activity 中使用的场景吧，为什么不能 Context 啊

以后有以后再加，不需要过度设计，而且大多数场景下需要调用的地方应该是可以获取到activity的

2024-11-14 03:33 UTC, merged